name: Scrape Game Cards

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 运行（北京时间 08:00）
  workflow_dispatch:      # 允许手动触发

permissions:
  contents: write  # 授予写入仓库的权限

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0  # 获取完整历史记录
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install Chrome browser
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
    
    - name: Install Python packages
      run: pip install -r requirements.txt
    
    - name: Run scraper
      run: python scraper.py
    
    - name: Commit and push changes using GitHub Script
      uses: actions/github-script@v6
      with:
        script: |
          // 配置 Git 用户
          execSync('git config --global user.name "GitHub Actions"');
          execSync('git config --global user.email "actions@users.noreply.github.com"');
          
          // 添加更改的文件
          execSync('git add data/game_cards.json');
          
          // 检查是否有更改
          const status = execSync('git status --porcelain').toString().trim();
          if (!status) {
            console.log('没有需要提交的更改');
            return;
          }
          
          // 创建提交
          const commitMessage = `自动更新游戏卡片数据: ${new Date().toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai' })}`;
          execSync(`git commit -m "${commitMessage}"`);
          
          // 推送更改
          try {
            execSync('git push');
            console.log('推送成功');
          } catch (pushError) {
            console.log('推送失败，尝试强制推送...');
            execSync('git push --force');
            console.log('强制推送成功');
          }
