name: Game Card Crawler

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间00:00运行（北京时间08:00）
  workflow_dispatch:     # 允许手动触发

jobs:
  crawl:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager beautifulsoup4
        
    - name: Install Microsoft Edge
      run: |
        sudo apt-get update
        sudo apt-get install -y microsoft-edge-dev
        
    - name: Run crawler
      run: python game_card_crawler.py
      
    - name: Archive results
      uses: actions/upload-artifact@v3
      with:
        name: game-cards-data
        path: game_cards.json
